# Generated by Django 5.0.3 on 2025-10-26 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealcalendar',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='mealcalendar',
            name='unique_user_recipe_date',
        ),
        migrations.RenameField(
            model_name='mealcalendar',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='mealcalendar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mealcalendar',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='mealcalendar',
            name='user',
        ),
        migrations.AddField(
            model_name='mealcalendar',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mealcalendar',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealcalendar',
            name='recipe_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealcalendar',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealcalendar',
            name='title',
            field=models.CharField(default='Untitled Meal', max_length=255),
            preserve_default=False,
        ),
    ]
