# Generated by Django 5.0.3 on 2025-10-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_mealcalendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcalendar',
            name='user',
        ),
    ]
